### ISSUE TITLE
Try/except handling for DOWNLOAD_FILES

### ISSUE THREAD

**Issue by bethac07** [DistributedScience/Distributed-CellProfiler#168] opened 2024-05-07 18:29 UTC

**Comment by ErinWeisbart** [comment] 2024-05-15 17:48
Duplicate of #162 ?

**Comment by bethac07** [comment] 2024-05-15 17:59
I vaguely thought in this case it was noisily failing, but @emiglietta would remember better than I would

**Closed** 2024-07-15 17:39 UTC
